# syntax=docker/dockerfile:1
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# NEXT_PUBLIC_* values are inlined into the client bundle at build time, not
# read at container runtime — they have to arrive as build args, not as
# Container App env vars. All of them are meant to be public (that's what
# NEXT_PUBLIC_ means), so no secret-handling needed here, just plumbing.
ARG NEXT_PUBLIC_REACT_APP_BACKEND_VERSION
ARG NEXT_PUBLIC_REACT_APP_BACKEND_ENDPOINT
ARG NEXT_PUBLIC_REACT_APP_BACKEND_SOCKET_ENDPOINT
ARG NEXT_PUBLIC_EMAILJS_SERVICE_ID
ARG NEXT_PUBLIC_EMAILJS_TEMPLATE_ID
ARG NEXT_PUBLIC_EMAILJS_PUBLIC_KEY
ARG NEXT_PUBLIC_CONTACT_EMAIL
ARG NEXT_PUBLIC_CONTACT_PHONE_NUMBER
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG NEXT_PUBLIC_UPLOAD_PRESET
ARG NEXT_PUBLIC_AGORA_APP_ID
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID

# Not real credentials -- src/app/api/sign-cloudinary-params/route.ts throws
# at module-load time if these are falsy, and Next.js evaluates route
# modules during `next build`'s page-data collection, before the container
# (and its real FE_CLOUDINARY_* secrets from Key Vault) ever exists. Any
# truthy placeholder satisfies that check; the real values only matter once
# the container actually calls the Cloudinary API at runtime.
ARG FE_CLOUDINARY_API_KEY=build-placeholder
ARG FE_CLOUDINARY_API_SECRET=build-placeholder

ENV FE_CLOUDINARY_API_KEY=$FE_CLOUDINARY_API_KEY \
    FE_CLOUDINARY_API_SECRET=$FE_CLOUDINARY_API_SECRET \
    NEXT_PUBLIC_REACT_APP_BACKEND_VERSION=$NEXT_PUBLIC_REACT_APP_BACKEND_VERSION \
    NEXT_PUBLIC_REACT_APP_BACKEND_ENDPOINT=$NEXT_PUBLIC_REACT_APP_BACKEND_ENDPOINT \
    NEXT_PUBLIC_REACT_APP_BACKEND_SOCKET_ENDPOINT=$NEXT_PUBLIC_REACT_APP_BACKEND_SOCKET_ENDPOINT \
    NEXT_PUBLIC_EMAILJS_SERVICE_ID=$NEXT_PUBLIC_EMAILJS_SERVICE_ID \
    NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=$NEXT_PUBLIC_EMAILJS_TEMPLATE_ID \
    NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=$NEXT_PUBLIC_EMAILJS_PUBLIC_KEY \
    NEXT_PUBLIC_CONTACT_EMAIL=$NEXT_PUBLIC_CONTACT_EMAIL \
    NEXT_PUBLIC_CONTACT_PHONE_NUMBER=$NEXT_PUBLIC_CONTACT_PHONE_NUMBER \
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME \
    NEXT_PUBLIC_UPLOAD_PRESET=$NEXT_PUBLIC_UPLOAD_PRESET \
    NEXT_PUBLIC_AGORA_APP_ID=$NEXT_PUBLIC_AGORA_APP_ID \
    NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID \
    NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY \
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
    NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID \
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
    NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID \
    NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
ENV PORT=3000
CMD ["node", "server.js"]
