/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
    },
    extend: {
      colors: {
        gray: {
          100: '#f7fafc',
          200: '#edf2f7',
          300: '#e2e8f0',
          400: '#cbd5e0',
          500: '#a0aec0',
          600: '#718096',
          700: '#4a5568',
          800: '#2d3748',
          900: '#1a202c',
        },
        blue: {
          100: '#ebf8ff',
          200: '#bee3f8',
          300: '#90cdf4',
          400: '#63b3ed',
          500: '#4299e1',
          600: '#3182ce',
          700: '#2b6cb0',
          800: '#2c5282',
          900: '#2a4365',
        },
        black: 'var(--black)',
        'foundation-bluedark': 'var(--foundation-bluedark)',
        'foundation-bluedark-active': 'var(--foundation-bluedark-active)',
        'foundation-bluedark-hover': 'var(--foundation-bluedark-hover)',
        'foundation-bluelight-active': 'var(--foundation-bluelight-active)',
        'foundation-bluelight-hover': 'var(--foundation-bluelight-hover)',
        'foundation-bluenormal-active': 'var(--foundation-bluenormal-active)',
        'foundation-bluenormal-hover': 'var(--foundation-bluenormal-hover)',
        'foundation-yellowdark': 'var(--foundation-yellowdark)',
        'foundation-yellowdark-active': 'var(--foundation-yellowdark-active)',
        'foundation-yellowdark-hover': 'var(--foundation-yellowdark-hover)',
        'foundation-yellowdarker': 'var(--foundation-yellowdarker)',
        'foundation-yellowlight': 'var(--foundation-yellowlight)',
        'foundation-yellowlight-active': 'var(--foundation-yellowlight-active)',
        'foundation-yellowlight-hover': 'var(--foundation-yellowlight-hover)',
        'foundation-yellownormal': 'var(--foundation-yellownormal)',
        'foundation-yellownormal-active':
          'var(--foundation-yellownormal-active)',
        'foundation-yellownormal-hover': 'var(--foundation-yellownormal-hover)',
        foundationbluedarker: 'var(--foundationbluedarker)',
        foundationbluelight: 'var(--foundationbluelight)',
        foundationbluenormal: 'var(--foundationbluenormal)',
      },
    },
  },
  plugins: [],
};
